---
title: MSc Health Data Science Project Title
author:
  - name: Student A Name
  - name: Student B Name
    affil: 1
affiliation:
  - num: 1
    address: School of Mathematical and Statistical Sciences, University of Galway
#logoleft_name: https&#58;//sport.universityofgalway.ie/assets/img/logo2.png

poster_height: "594mm"
poster_width: "841mm"
column_numbers: 4
column_margins: "0.5in"	
primary_colour:	"#a80050"	# Secondary colour use for poster design.
secondary_colour:	"#84003d"	# Main colour used for poster design.
accent_colour:	"#e6007e"	# A third colour option.
author_textcol: "white"
title_textsize: "90pt"
author_textsize: "60pt"
body_textsize: "25pt"
output: 
  posterdown::posterdown_html:
    self_contained: true
    pandoc_args: --mathjax
    number_sections: false
knit: pagedown::chrome_print
---

```{css, echo=FALSE}
div.logo_left{
  width: 20%;
}
div.poster_title{
  width: 80%;
}
.section h4 {
    break-after: column;
}
div.footnotes {
    font-size: 18pt;
}
```

<!-- Don't change anything above, except the title and author names, unless you know what you are doing. -->

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      tidy = FALSE,
                      message = FALSE,
                      fig.align = 'center',
                      out.width = "100%")
options(knitr.table.format = "html") 
# Load any additional libraries here
library(tidyverse)
library(plotly)
library(kableExtra)
library(pagedown)
```

# Background and Problem

Malaria remains a critical public health challenge in West Africa, yet accurate data at the local district level is often scarce. While Demographic and Health Surveys (DHS) provide essential data on prevalence and intervention coverage, they are designed for national-level precision[^1]. when disaggregated to the district (Admin 2) level, these direct estimates rely on small sample sizes, resulting in noisy estimates with high variability[^2].

To overcome this data scarcity, this project employs the Fay-Herriot model, a standard Area-Level Small Area Estimation (SAE) method. This approach borrows strength from auxiliary data, such as census demographics and climate variables like rainfall and altitude, to generate smoothed, robust estimates of malaria burden and intervention coverage for every district. Beyond simple estimation, we leverage these robust values to investigate the causal effect of interventions, adjusting for confounding variables to model counterfactual scenarios and predict how different strategies could reduce the future malaria burden[^3].

## Objectives of Project

1. To combine survey, census and climate data to make Small Area level estimates of malaria incidence, ACT uptake and ITN coverage in select west African countries using the Fay-Herriot model

2. To use the estimate obtained from SAE to estimate the casual effects of malaria interventions (ACT, ITN, Medical treatment for fever) on small area level malaria burden while adjusting for confounding variables

3. To use the causal estimate to carry out projections based on different counter factual scenarios (e.g., if 80% of the people were sleeping under nets)

# Data Sources and Datasets



<!-- This #### below causes the columns to break -->

<!-- You can change where you put these breaks, and the "column_numbers: 4" argument in the YAMLS header to change the layout of the poster, with care! -->

#### 

# Data Description



#### 

# Next Project Steps

Data Integration & Processing

· Survey Data (DHS): Calculating direct weighted estimates for malaria prevalence (positive test results), ACT uptake, and ITN coverage at the Admin 2 (District) level.

· Climate Sources: Rainfall, average temperature, altitude, and proximity to water bodies (swamps).

· Census/Socio-economic Sources: Poverty levels, urban/rural classification, and population density.

Small Area Estimation (Objective 1)

· Fay-Herriot Model: Using the Fay-Herriot (FH) model to smooth the noisy direct estimates from the DHS survey. Since we are dealing with rates/counts (cases

per thousand), we will implement a Poisson regression variant of the Fay-Herriot model.

· Random Effects: We will fit and compare two model specifications using the SAE package in R:

1. Independent Random Effects: Assumes district-specific variations are unrelated.

2. Spatial Random Effects: Accounts for the fact that neighboring districts likely have similar malaria rates.
Causal Inference (Objective 2)

· Causal Estimation: We will use the smoothed small area estimates (from Step 2) as the input variables. We will estimate the causal effect of interventions (ACT, ITN) on the malaria burden.

· Confounder Adjustment: The model will adjust for confounding variables to isolate the true effect of the interventions.

Counterfactual Projections (Objective 3)

Static Scenario Modelling: We will perform counterfactual analysis i.e. using the causal coefficients estimated in Step 3 to predict what the malaria burden would be under different hypothetical scenarios (e.g., If ITN coverage were increased to 80%...).

Visualization: We will produce maps comparing the Current Status vs. Projected Status to identify the most effective intervention strategy over a Shiny App.

[^1]: Corsi, D. J., Neuman, M., Finlay, J. E., & Subramanian, S.. (2012). Demographic and health surveys: a profile. International Journal of Epidemiology, 41(6), 1602–1613. https://doi.org/10.1093/ije/dys184
[^2]: Rao, Jnk, and Isabel Molina. Small Area Estimation /. Second. Hoboken, New Jersey : Wiley, 2015. Print.
[^3]: Weiss, D. J., et al. (2019). "Mapping the global prevalence, incidence, and mortality of Plasmodium falciparum, 2000–17: a spatial and temporal modelling study." The Lancet 394(10195): 322–331.


# GitHub

The code and datasets for this project can be viewed at our GitHub repository here: <https://github.com/>



# References



